// --- DATA CONSTANTS ---
export const colorOptions = [
  "Eerie Black (#0D0D0D)",
  "Bright Imperial Blue (#001379)",
  "Crimson Red (#9F0D17)",
  "Dark Roast (#2B1B17)",
  "Tropical Teal (#2B939A)",
  "Azure Blue (#066CBA)",
  "Pure White (#EDEDED)",
  "Magenta (#FF00FF)",
  "Deep Teal Green (#077C64)",
  "Midnight Blue (#111833)",
  "Vivid Burgundy (#9D0F2E)",
  "Charcoal Gray (#3A3A3A)",
  "Bubblegum Pink (#F6AAC4)",
  "Camel Beige (#977A53)",
  "Cyber Yellow (#F0D003)",
  "Golden Marigold (#E9980C)",
  "Rich Burgundy (#380D13)",
  "Regal Purple (#371141)",
  "Aubergine (#28121E)",
  "Army Green (#282B17)",
  "Deep Crimson (#571B1C)",
  "Warm Off-White (#FAF9F6)",
  "Neon Orange (#EB3F11)",
  "Slate Teal (#54767E)",
  "Blue-Gray (#7E909C)",
  "Mossy Olive (#75735C)",
  "Soft Cream (#E9D7BA)",
  "Pastel Peach (#EFCBB5)",
  "Cocoa Brown (#825542)",
  "Brick Red (#832B20)",
  "Forest Green (#445D3E)",
  "Coral Red (#F1454A)",
  "Marsala (#5E241C)",
  "Pistachio Green (#98C588)",
  "Neon Green (#7ED240)",
  "Dusty Lavender (#966F90)",
  "Pastel Blue (#7EAADE)",
  "Light Gray (#9EADB6)",
  "Soft Peach Coral (#F4978E)",
  "Golden Ochre (#DF9C3E)",
  "Sage Teal (#4F9487)",
  "Dusty Rose Mauve (#CFACB1)",
  "Taupe Greige (#AC9891)",
  "Dusty Rose Pink (#C28899)",
  "Soft Lilac (#BBA0B1)",
  "Deep Forest Green (#094F3B)",
  "Fuchsia Pink (#B5486B)",
  "Morning Sky Blue (#A2EBFF)",
  "Khaki Beige (#A99C8C)",
];

export const aesthetics = [
  "Art Deco",
  "Avant-Garde",
  "Biomorphic",
  "Bohemian (Boho)",
  "Cyberpunk",
  "Futuristic",
  "Gothic",
  "Industrial",
  "Maximalist",
  "Minimalist",
  "Nautical",
  "Preppy",
  "Rustic / Artisanal",
  "Steampunk",
  "Streetwear",
  "Whimsical",
];

export const productCatalog = {
  Bags: [
    "Backpack",
    "Baguette bag",
    "Belt bag (fanny pack / waist bag)",
    "Bowling bag",
    "Bucket bag",
    "Clutch",
    "Crossbody bag",
    "Duffle bag",
    "Frame bag",
    "Hobo bag",
    "Laptop bag",
    "Messenger bag",
    "Minaudière",
    "Saddle bag",
    "Satchel",
    "Shoulder bag",
    "Sling bag",
    "Tote bag",
    "Top-handle bag",
    "Wristlet",
  ],
  Footwear: [
    "Ballet flats",
    "Clogs",
    "Combat boots",
    "Derby shoes",
    "Espadrilles",
    "Gladiator sandals",
    "High-top sneakers",
    "Kitten heels",
    "Loafers",
    "Mary Janes",
    "Mules",
    "Oxfords",
    "Platform heels",
    "Sandals",
    "Slip-ons",
    "Slingbacks",
    "Sneakers",
    "Wedges",
  ],
  "Wallets & Small Goods": [
    "Bi-fold fabric wallet",
    "Card pouch",
    "Coin pouch",
    "Fabric clutch",
    "Fabric organizer pouch",
    "Folded travel wallet",
    "ID holder",
    "Key holder pouch",
    "Lanyard pouch",
    "Mini zip pouch",
    "Passport pouch",
    "Phone pouch",
    "Slim fabric wallet",
    "Travel document pouch",
    "Wristlet pouch",
    "Zip wallet",
    "Zip utility pouch",
  ],
};

export const countries = {
  Belgium: {
    code: "be",
    designers: [
      "Dries Van Noten",
      "Raf Simons",
      "Ann Demeulemeester",
      "Martin Margiela",
      "Walter Van Beirendonck",
    ],
  },
  Brazil: {
    code: "br",
    designers: [
      "Francisco Costa",
      "Adriana Degreas",
      "Oskar Metsavaht",
      "Alexandre Herchcovitch",
      "Samuel Cirnansck",
    ],
  },
  Canada: {
    code: "ca",
    designers: [
      "Brian Bailey",
      "Dsquared2 (Dean & Dan Caten alt-origin CA)",
      "Marie Saint Pierre",
      "Erin Kleinberg",
      "Ted Baker (UK/CA connection)",
    ],
  },
  China: {
    code: "cn",
    designers: [
      "Guo Pei",
      "Wang Zhi",
      "Masha Ma",
      "Chen Shuzhi",
      "Angel Chen"
    ],
  },
  France: {
    code: "fr",
    designers: [
      "Louis Vuitton",
      "Coco Chanel",
      "Thierry Hermes",
      "Christian Dior",
      "Celine Vipiana",
    ],
  },
  Germany: {
    code: "de",
    designers: [
      "Wolfgang Joop",
      "Lutz Huelle",
      "Leyla Piedayesh",
      "Heinz Oestergaard",
      "Jil Sander",
    ],
  },
  "Germany-Alternate / Austria": {
    code: "at",
    designers: [
      "Willy Bogner",
      "A:Sense (Brand)",
      "Annemarie Heinrich",
      "Helmut Lang (origin Austria-Canada)",
      "Lena Hoschek",
    ],
  },
  India: {
    code: "in",
    designers: [
      "Ritu Kumar",
      "Sabyasachi Mukherjee",
      "Manish Malhotra",
      "Gautam Sinha",
      "Anita Dongre",
    ],
  },
  Indonesia: {
    code: "id",
    designers: [
      "Tex Saverio",
      "Biyan Wanaatmadja",
      "Toton Januar",
      "Lulu Lutfi Labibi",
      "Rinaldy Yunardi",
    ],
  },
  Italy: {
    code: "it",
    designers: [
      "Guccio Gucci",
      "Mario Prada",
      "Adele Fendi",
      "Edoardo Fendi",
      "Valentino Garavani",
    ],
  },
  Japan: {
    code: "jp",
    designers: [
      "Issey Miyake",
      "Kichizo Yoshida",
      "Rei Kawakubo",
      "Jun Takahashi",
      "Kunihiko Morinaga",
    ],
  },
  Mexico: {
    code: "mx",
    designers: [
      "Ricardo Seco",
      "Pineda Covalin",
      "Carla Fernández",
      "Patricio Campillo",
      "Julio Escandón",
    ],
  },
  Nigeria: {
    code: "ng",
    designers: [
      "Zashadu",
      "Lisa Folawiyo",
      "Amaka Osakwe",
      "Ozwald Boateng",
      "Titi Adesa",
    ],
  },
  Russia: {
    code: "ru",
    designers: [
      "Slava Zaitsev",
      "Valentin Yudashkin",
      "Ulyana Sergeenko",
      "Yulia Yanina",
      "Alexander Terekhov",
    ],
  },
  "Saudi Arabia": {
    code: "sa",
    designers: [
      "Arwa Al Banawi",
      "Hatem Alakeel",
      "Hunaida Serafi",
      "Noor Al Hassan",
      "Alya Bin Omair",
    ],
  },
  "South Africa": {
    code: "za",
    designers: [
      "Laduma Ngxokolo",
      "Palesa Mokubung",
      "David Tlale",
      "Rich Mnisi",
      "Marianne Fassler",
    ],
  },
  "South Korea": {
    code: "kr",
    designers: [
      "Wooyoungmi",
      "Juun.J",
      "Rok Hwang",
      "Lie Sang Bong",
      "Minju Kim",
    ],
  },
  Spain: {
    code: "es",
    designers: [
      "Cristobal Balenciaga",
      "Paco Rabanne",
      "Manolo Blahnik",
      "Adolfo Dominguez",
      "Agatha Ruiz de la Prada",
    ],
  },
  Sweden: {
    code: "se",
    designers: [
      "Josef Frank",
      "Astrid Sampe",
      "Stig Lindberg",
      "House of Dagmar",
      "Ida Sjöstedt",
    ],
  },
  Switzerland: {
    code: "ch",
    designers: [
      "Akris",
      "Bally (fashion-acc/history)",
      "Frederique Constant (watch/fashion crossover)",
      "Viadukt (bags brand)",
      "Bally Switzerland designers",
    ],
  },
  Turkey: {
    code: "tr",
    designers: [
      "Cemil İpekçi",
      "Atıl Kutoğlu",
      "Dilara Fındıkoğlu",
      "Bora Aksu",
      "Dilek Hanif",
    ],
  },
  "United Kingdom": {
    code: "gb",
    designers: [
      "Roger Saul",
      "Alexander McQueen",
      "Vivienne Westwood",
      "Thomas Burberry",
      "Anya Hindmarch",
    ],
  },
  "United States": {
    code: "us",
    designers: [
      "Miles Cahn",
      "Lillian Cahn",
      "Michael Kors",
      "Marc Jacobs",
      "Kate Spade",
    ],
  },
};
